server:
  port: "0.0.0.0:18082"

# 消息接收客户端，支持配置数组同时发送
client:
  - wechat
  - dingtalk
  - feishu

notifiers:
  wechat:
    webhook_url: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxxxxxxxxxxxxxxxxxxxxx"
  dingtalk:
    webhook_url: "https://oapi.dingtalk.com/robot/send?access_token=xxxxxxxxxxxxxxxxxxxxxxxxx"
  feishu:
    webhook_url: "https://open.feishu.cn/open-apis/bot/v2/hook/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# 告警过滤规则配置（可选）
filter:
  # 基于告警名称的过滤规则
  alert_name:
    # 包含规则：只有匹配这些规则的告警才会被发送（支持通配符*）
    include:
      - "HighCPU*"              # 匹配以HighCPU开头的告警
      - "*Memory*"              # 匹配包含Memory的告警  
      - "DiskSpaceLow"          # 精确匹配
      - "DatabaseConnectionError" # 精确匹配
      # - "*"                   # 匹配所有告警（如果需要允许所有告警名称）
    # 排除规则：匹配这些规则的告警不会被发送（优先级高于include）
    exclude:
      - "*Test*"                # 排除包含Test的告警
      - "DebugAlert"            # 排除调试告警
      - "InfoInhibitor"         # 排除信息抑制告警
      
  # 基于告警级别的过滤规则  
  severity:
    # 包含规则：只发送这些级别的告警
    include:
      - "emergency"             # 紧急告警
      - "critical"              # 严重告警
      - "warning"               # 警告告警
      # - "info"                 # 信息告警（可选）
    # 排除规则：不发送这些级别的告警
    exclude:
      - "info"                  # 排除信息级别告警
      - "none"                  # 排除none级别
      
# 说明：
# 1. 如果不配置filter部分，默认会发送所有告警（除了severity为none的）
# 2. 支持通配符：* 匹配任意字符，如 "High*" 匹配以High开头的所有告警名称
# 3. exclude规则优先级高于include规则
# 4. alert_name和severity规则都必须通过，告警才会被发送
# 5. 可以只配置其中一种过滤规则，另一种不配置表示不限制